import type { StoredBooking, StoredService } from "./store";
import type { AppNotification } from "@/components/NotificationsDropdown";

const SEED_KEY = "needly_seeded_v2";

const now = Date.now();
const daysAgo = (d: number) => new Date(now - d * 86_400_000).toISOString();

const SEED_BOOKINGS: StoredBooking[] = [
  {
    id: "SBK001",
    serviceId: "t1",
    serviceTitle: "Premium WordPress Website Development",
    category: "Technology",
    categoryIcon: "fas fa-laptop-code",
    vendorName: "Tharindu Perera",
    vendorPhone: "+94771234567",
    vendorInitial: "T",
    vendorVerified: true,
    customerName: "Kamani Rathnayake",
    customerPhone: "+94712345678",
    date: new Date(now + 5 * 86_400_000).toISOString().split("T")[0],
    time: "10:00",
    notes: "Need e-commerce functionality with payment gateway",
    extraData: { "Project Brief": "Clothing store website", "Pages Required": "8-10 pages" },
    price: 35000,
    district: "Colombo",
    status: "pending",
    createdAt: daysAgo(1),
  },
  {
    id: "SBK002",
    serviceId: "l2",
    serviceTitle: "AC Repair & Full Servicing",
    category: "Repairs",
    categoryIcon: "fas fa-snowflake",
    vendorName: "Ravi Mendis",
    vendorPhone: "+94762345678",
    vendorInitial: "R",
    vendorVerified: true,
    customerName: "Suresh Bandara",
    customerPhone: "+94723456789",
    date: new Date(now + 2 * 86_400_000).toISOString().split("T")[0],
    time: "14:00",
    notes: "Two units — split AC in living room and bedroom",
    extraData: { "AC Brand": "Daikin", "Number of Units": "2" },
    price: 6500,
    district: "Gampaha",
    status: "confirmed",
    createdAt: daysAgo(3),
  },
  {
    id: "SBK003",
    serviceId: "l7",
    serviceTitle: "Professional Car Full Detailing",
    category: "Vehicle Service",
    categoryIcon: "fas fa-car-side",
    vendorName: "Pradeep Nishantha",
    vendorPhone: "+94777654321",
    vendorInitial: "P",
    vendorVerified: true,
    customerName: "Dilani Fernando",
    customerPhone: "+94734567890",
    date: new Date(now - 1 * 86_400_000).toISOString().split("T")[0],
    time: "09:00",
    notes: "Sedan, dark blue — exterior + interior",
    extraData: { "Vehicle Make & Model": "Toyota Axio 2017", "Registration Number": "CAF-8821" },
    price: 9500,
    district: "Colombo",
    status: "in_progress",
    createdAt: daysAgo(5),
  },
  {
    id: "SBK004",
    serviceId: "t2",
    serviceTitle: "Luxury Home Deep Cleaning",
    category: "Home Services",
    categoryIcon: "fas fa-gem",
    vendorName: "Nirmala Jayawardena",
    vendorPhone: "+94779876543",
    vendorInitial: "N",
    vendorVerified: true,
    customerName: "Kavinda Rajapaksa",
    customerPhone: "+94745678901",
    date: daysAgo(14).split("T")[0],
    time: "08:00",
    notes: "",
    extraData: { "Property Size": "3 bed / 2 bath", "Special Requests": "Focus on kitchen and bathrooms" },
    price: 12500,
    district: "Kandy",
    status: "completed",
    createdAt: daysAgo(16),
  },
  {
    id: "SBK005",
    serviceId: "t3",
    serviceTitle: "A/L Combined Maths Intensive",
    category: "Tuition",
    categoryIcon: "fas fa-fire",
    vendorName: "Kasun Jayasinghe",
    vendorPhone: "+94766543210",
    vendorInitial: "K",
    vendorVerified: true,
    customerName: "Amali Perera",
    customerPhone: "+94756789012",
    date: daysAgo(25).split("T")[0],
    time: "17:00",
    notes: "Student sitting A/L in August",
    extraData: { "Student Level": "A/L Year 2", "Subjects": "Combined Maths, Physics" },
    price: 4500,
    district: "Galle",
    status: "completed",
    createdAt: daysAgo(28),
  },
  {
    id: "SBK006",
    serviceId: "l5",
    serviceTitle: "Wedding Photography Package",
    category: "Photography",
    categoryIcon: "fas fa-camera",
    vendorName: "Sumudu Fernando",
    vendorPhone: "+94788901234",
    vendorInitial: "S",
    vendorVerified: true,
    customerName: "Malith de Silva",
    customerPhone: "+94767890123",
    date: daysAgo(40).split("T")[0],
    time: "07:00",
    notes: "Church + reception coverage, 8 hours",
    extraData: { "Venue": "Colombo Hilton Ballroom", "Guest Count": "250" },
    price: 75000,
    district: "Colombo",
    status: "completed",
    createdAt: daysAgo(45),
  },
  {
    id: "SBK007",
    serviceId: "l3",
    serviceTitle: "Graphic Design — Logo & Brand Kit",
    category: "Design",
    categoryIcon: "fas fa-pen-nib",
    vendorName: "Tharindu Perera",
    vendorPhone: "+94771234567",
    vendorInitial: "T",
    vendorVerified: true,
    customerName: "Ruwan Jayakody",
    customerPhone: "+94778901234",
    date: daysAgo(60).split("T")[0],
    time: "11:00",
    notes: "Startup brand — modern, minimal",
    extraData: { "Industry": "Tech / SaaS", "Preferred Colors": "Blue + White" },
    price: 18000,
    district: "Colombo",
    status: "completed",
    createdAt: daysAgo(62),
  },
  {
    id: "SBK008",
    serviceId: "l1",
    serviceTitle: "Emergency Plumbing Repair",
    category: "Plumbing",
    categoryIcon: "fas fa-wrench",
    vendorName: "Sunil Abeysekara",
    vendorPhone: "+94755432109",
    vendorInitial: "S",
    vendorVerified: false,
    customerName: "Priya Srikanth",
    customerPhone: "+94789012345",
    date: daysAgo(8).split("T")[0],
    time: "21:00",
    notes: "Pipe burst — urgent",
    extraData: { "Issue Type": "Burst pipe under kitchen sink" },
    price: 4500,
    district: "Colombo",
    status: "cancelled",
    createdAt: daysAgo(9),
    isEmergency: true,
  },
];

const SEED_SERVICES: StoredService[] = [
  {
    id: "SVC001",
    title: "Premium WordPress Website Development",
    category: "Technology",
    categoryIcon: "fas fa-laptop-code",
    description: "Full-stack WordPress development including custom themes, plugins, WooCommerce, and SEO setup. Delivered with mobile-responsive design and 3 months of free support.",
    price: 35000,
    priceUnit: "per project",
    type: "Remote / On-site",
    tags: ["wordpress", "website", "ecommerce", "seo"],
    district: "Colombo",
    status: "active",
    views: 284,
    orders: 12,
    rating: 4.9,
    createdAt: daysAgo(90),
  },
  {
    id: "SVC002",
    title: "Logo Design & Brand Identity Kit",
    category: "Design",
    categoryIcon: "fas fa-pen-nib",
    description: "Professional logo design with 3 concepts, unlimited revisions until satisfied. Includes full brand kit: business card, letterhead, social media templates (PNG, AI, PDF formats).",
    price: 8500,
    priceUnit: "per project",
    type: "Remote",
    tags: ["logo", "branding", "graphic-design", "identity"],
    district: "Colombo",
    status: "active",
    views: 197,
    orders: 8,
    rating: 4.8,
    createdAt: daysAgo(75),
  },
  {
    id: "SVC003",
    title: "Social Media Content Package",
    category: "Marketing",
    categoryIcon: "fas fa-bullhorn",
    description: "Monthly social media management for Facebook and Instagram. Includes 20 posts, story templates, hashtag research, and weekly performance reports.",
    price: 15000,
    priceUnit: "per month",
    type: "Remote",
    tags: ["social-media", "facebook", "instagram", "marketing"],
    district: "Colombo",
    status: "active",
    views: 142,
    orders: 5,
    rating: 4.7,
    createdAt: daysAgo(60),
  },
  {
    id: "SVC004",
    title: "Data Entry & Excel Automation",
    category: "Data & Admin",
    categoryIcon: "fas fa-table",
    description: "Fast, accurate data entry, spreadsheet cleanup, and Excel/Google Sheets automation with formulas and macros. Perfect for businesses needing efficient admin support.",
    price: 2500,
    priceUnit: "per hour",
    type: "Remote",
    tags: ["data-entry", "excel", "admin", "automation"],
    district: "Online",
    status: "paused",
    views: 89,
    orders: 3,
    rating: 4.6,
    createdAt: daysAgo(45),
  },
  {
    id: "SVC005",
    title: "SEO Audit & Optimization",
    category: "Technology",
    categoryIcon: "fas fa-magnifying-glass-chart",
    description: "Complete website SEO audit covering technical SEO, on-page optimization, keyword research, backlink analysis, and a 90-day action plan to improve Google rankings.",
    price: 22000,
    priceUnit: "per project",
    type: "Remote",
    tags: ["seo", "google", "website", "ranking"],
    district: "Colombo",
    status: "active",
    views: 156,
    orders: 6,
    rating: 4.9,
    createdAt: daysAgo(30),
  },
];

const SEED_NOTIFICATIONS: AppNotification[] = [
  {
    id: "SNOTIF001",
    type: "booking_new",
    title: "New Booking Request",
    body: "Kamani R. booked your WordPress Development service for next week.",
    link: "/dashboard/seller/orders",
    createdAt: daysAgo(1),
    read: false,
  },
  {
    id: "SNOTIF002",
    type: "booking_confirmed",
    title: "Booking Confirmed",
    body: "Your AC repair with Ravi M. is confirmed for tomorrow at 2:00 PM.",
    link: "/dashboard/buyer/orders",
    createdAt: daysAgo(3),
    read: false,
  },
  {
    id: "SNOTIF003",
    type: "booking_completed",
    title: "Order Completed",
    body: "Home Deep Cleaning by Nirmala J. has been marked as completed.",
    link: "/dashboard/buyer/orders",
    createdAt: daysAgo(14),
    read: true,
  },
  {
    id: "SNOTIF004",
    type: "review",
    title: "New 5-Star Review",
    body: "Kavinda R. left you a 5-star review: \"Excellent work, very professional!\"",
    link: "/dashboard/seller",
    createdAt: daysAgo(15),
    read: true,
  },
  {
    id: "SNOTIF005",
    type: "message",
    title: "New Message",
    body: "Dilani F. sent you a message about the car detailing booking.",
    link: "/dashboard/seller/inbox",
    createdAt: daysAgo(5),
    read: true,
  },
];

const SEED_FEED_POSTS = [
  {
    id: "SFEED001",
    author: "Tharindu Perera",
    initial: "T",
    role: "Pro Seller",
    verified: true,
    location: "Colombo",
    category: "Technology",
    categoryIcon: "fas fa-laptop-code",
    postedAt: new Date(daysAgo(2)).toISOString(),
    title: "🚀 WordPress & WooCommerce Sites — Starting Rs. 25,000",
    description: "Delivered 12 websites this month alone! I build fast, SEO-optimised WordPress sites for businesses across Sri Lanka. WhatsApp me for a free consultation and quote.",
    price: 25000,
    priceType: "Negotiable",
    tags: ["wordpress", "website", "ecommerce"],
    likes: 47,
    shares: 12,
    contactPhone: "+94771234567",
    contactWhatsapp: "+94771234567",
    comments: [],
  },
  {
    id: "SFEED002",
    author: "Nirmala Jayawardena",
    initial: "N",
    role: "Individual Seller",
    verified: true,
    location: "Kandy",
    category: "Home Services",
    categoryIcon: "fas fa-broom",
    postedAt: new Date(daysAgo(1)).toISOString(),
    title: "Deep Cleaning Service — Kandy & Surroundings",
    description: "Professional home & office deep cleaning using eco-friendly products. Team of 3. Full 3-bedroom house done in 4 hours. Book now for a sparkling clean home!",
    price: 8500,
    priceType: "Fixed",
    tags: ["cleaning", "home", "kandy"],
    likes: 31,
    shares: 8,
    contactWhatsapp: "+94779876543",
    comments: [],
  },
  {
    id: "SFEED003",
    author: "Sumudu Fernando",
    initial: "S",
    role: "Business",
    verified: true,
    location: "Colombo",
    category: "Photography",
    categoryIcon: "fas fa-camera",
    postedAt: new Date(daysAgo(4)).toISOString(),
    title: "Wedding Photography — Limited Dates Left for 2026",
    description: "Award-winning wedding photography studio. Full-day coverage, 500+ edited photos, same-day preview album, and a beautifully designed photo book. Only 3 dates remaining!",
    price: 75000,
    priceType: "Fixed",
    tags: ["wedding", "photography", "colombo"],
    likes: 89,
    shares: 34,
    contactWhatsapp: "+94788901234",
    comments: [],
  },
];

export function seedLocalStorage() {
  if (localStorage.getItem(SEED_KEY)) return;

  // Bookings
  const existingBookings = (() => { try { return JSON.parse(localStorage.getItem("needly_bookings") ?? "[]"); } catch { return []; } })();
  if (existingBookings.length === 0) {
    localStorage.setItem("needly_bookings", JSON.stringify(SEED_BOOKINGS));
  }

  // Services
  const existingServices = (() => { try { return JSON.parse(localStorage.getItem("needly_my_services") ?? "[]"); } catch { return []; } })();
  if (existingServices.length === 0) {
    localStorage.setItem("needly_my_services", JSON.stringify(SEED_SERVICES));
  }

  // Notifications
  const existingNotifs = (() => { try { return JSON.parse(localStorage.getItem("needly_notifications") ?? "[]"); } catch { return []; } })();
  if (existingNotifs.length === 0) {
    localStorage.setItem("needly_notifications", JSON.stringify(SEED_NOTIFICATIONS));
  }

  // Feed posts
  const existingFeed = (() => { try { return JSON.parse(localStorage.getItem("needly_feed_posts") ?? "[]"); } catch { return []; } })();
  if (existingFeed.length === 0) {
    localStorage.setItem("needly_feed_posts", JSON.stringify(SEED_FEED_POSTS));
  }

  localStorage.setItem(SEED_KEY, "1");
}
